// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB45zMFVkugdTz6EQ_8oS8gl01ZKfbhTt8',
    appId: '1:355681786103:web:af4976c98e94604a2cdbf2',
    messagingSenderId: '355681786103',
    projectId: 'learning-9329e',
    authDomain: 'learning-9329e.firebaseapp.com',
    databaseURL: 'https://learning-9329e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learning-9329e.appspot.com',
    measurementId: 'G-E2CNGSYRYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsKg8lO_OYhZa-DSwItNpIodDfC5KF0MY',
    appId: '1:355681786103:android:f79ef29f98f323cd2cdbf2',
    messagingSenderId: '355681786103',
    projectId: 'learning-9329e',
    databaseURL: 'https://learning-9329e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learning-9329e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3xNktihkkRNVwT4H6IZwzC8Yvr-y2XPY',
    appId: '1:355681786103:ios:0c1d9d4a0f1d12cf2cdbf2',
    messagingSenderId: '355681786103',
    projectId: 'learning-9329e',
    databaseURL: 'https://learning-9329e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learning-9329e.appspot.com',
    iosClientId: '355681786103-8846itfkp2o21umj36tvskvpn6adodk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3xNktihkkRNVwT4H6IZwzC8Yvr-y2XPY',
    appId: '1:355681786103:ios:e1702e46bc7a0bff2cdbf2',
    messagingSenderId: '355681786103',
    projectId: 'learning-9329e',
    databaseURL: 'https://learning-9329e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learning-9329e.appspot.com',
    iosClientId: '355681786103-rbjsuj32su1lee5radhv09r12dpjt9dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.learning.RunnerTests',
  );
}
